apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: first-secret
  annotations:
    kustomize.config.k8s.io/behavior: merge
    kustomize.config.k8s.io/needs-hash: 'true'
data:
  myconfig: ewoJImpzb25rZXkiOiBbCgkJIkVOQ1tBRVMyNTZfR0NNLGRhdGE6aDQ3M2h1eGlJWU1QbGc9PSxpdjpoVkc2cTBjTEc3RDBkUUpBcGxMRTRVT1ZjNnlyaGFmQnpTd1R1bmlPK2hzPSx0YWc6MEtzN01oMnJvYmoxa1JLY0tDTnpsQT09LHR5cGU6c3RyXSIsCgkJIkVOQ1tBRVMyNTZfR0NNLGRhdGE6cDdJUEsrczB1MzU5QVE9PSxpdjp6RGxhem12WG8rK3YyckRZUDU2LzhjM0xXSW9HMWFzUlJFdXo0S2JMWDdzPSx0YWc6YlRRK3FCNVZxckk0M04wLzlDWmRZdz09LHR5cGU6c3RyXSIKCV0KfQ==
  otherconfig: ewoJImpzb25rZXkiOiBbCgkJIkVOQ1tBRVMyNTZfR0NNLGRhdGE6aDQ3M2h1eGlJWU1QbGc9PSxpdjpoVkc2cTBjTEc3RDBkUUpBcGxMRTRVT1ZjNnlyaGFmQnpTd1R1bmlPK2hzPSx0YWc6MEtzN01oMnJvYmoxa1JLY0tDTnpsQT09LHR5cGU6c3RyXSIsCgkJIkVOQ1tBRVMyNTZfR0NNLGRhdGE6cDdJUEsrczB1MzU5QVE9PSxpdjp6RGxhem12WG8rK3YyckRZUDU2LzhjM0xXSW9HMWFzUlJFdXo0S2JMWDdzPSx0YWc6YlRRK3FCNVZxckk0M04wLzlDWmRZdz09LHR5cGU6c3RyXSIKCV0KfQ==
  foo: RU5DW0FFUzI1Nl9HQ00sZGF0YTp0V2F6LGl2Ok44T1ByMXZmWG92VmR5aHpFWjlCSldyK01QZGxZeFFvU0pReEJ5bVNLWUU9LHRhZzpxbG90SzBqSDJQL2VLM29rdUZJMEtRPT0sdHlwZTpzdHJd
  multiple: RU5DW0FFUzI1Nl9HQ00sZGF0YTpvMG1rblc3T01Zelh3OGh0RHJZPSxpdjpnazVhaklTZmJjMGRubWtmbEN1cUtXN3BwaXZOZS9VL1ZmYnZyaDZnZTNvPSx0YWc6SnNJMWw2U3dWckd0RHlBcDNiZGc0Zz09LHR5cGU6c3RyXQ==
  trailing: RU5DW0FFUzI1Nl9HQ00sZGF0YTp0Ly9OdjlLYSxpdjpaM1RyNlM3Skh6RUs3djZUVll4eEJaMUxaWTdwNGcrS0FIMEJ6VERBYnVzPSx0YWc6a0pLSDlxTVZCbFBOVFloWU43RU44Zz09LHR5cGU6c3RyXQ==
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: second-secret
  annotations:
    kustomize.config.k8s.io/needs-hash: 'true'
data:
  foo: RU5DW0FFUzI1Nl9HQ00sZGF0YTp0V2F6LGl2Ok44T1ByMXZmWG92VmR5aHpFWjlCSldyK01QZGxZeFFvU0pReEJ5bVNLWUU9LHRhZzpxbG90SzBqSDJQL2VLM29rdUZJMEtRPT0sdHlwZTpzdHJd
  multiple: RU5DW0FFUzI1Nl9HQ00sZGF0YTpvMG1rblc3T01Zelh3OGh0RHJZPSxpdjpnazVhaklTZmJjMGRubWtmbEN1cUtXN3BwaXZOZS9VL1ZmYnZyaDZnZTNvPSx0YWc6SnNJMWw2U3dWckd0RHlBcDNiZGc0Zz09LHR5cGU6c3RyXQ==
  trailing: RU5DW0FFUzI1Nl9HQ00sZGF0YTp0Ly9OdjlLYSxpdjpaM1RyNlM3Skh6RUs3djZUVll4eEJaMUxaWTdwNGcrS0FIMEJ6VERBYnVzPSx0YWc6a0pLSDlxTVZCbFBOVFloWU43RU44Zz09LHR5cGU6c3RyXQ==
